openapi: 3.0.3
info:
  title: Booking Service API
  description: Manages bookings, rental statuses, and cancellations
  version: 1.0.0

servers:
  - url: https://api.laviolin.com/v1

security:
  - bearerAuth: []

paths:
  /bookings:
    post:
      summary: Create booking
      operationId: createBooking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [instrumentId, startDate, endDate, deliveryMethod]
              properties:
                instrumentId:
                  type: string
                  format: uuid
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                message:
                  type: string
                deliveryMethod:
                  type: string
                  enum: [pickup, delivery]
                deliveryAddress:
                  type: object
      responses:
        '201':
          description: Booking created
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking:
                    $ref: '#/components/schemas/Booking'
                  paymentIntentId:
                    type: string
        '400':
          description: Invalid dates or validation error
        '409':
          description: Date conflict - instrument unavailable

  /bookings/{bookingId}:
    get:
      summary: Get booking details
      operationId: getBooking
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingDetail'
        '403':
          description: Not authorized to view this booking
        '404':
          description: Booking not found

  /bookings/{bookingId}/status:
    patch:
      summary: Update booking status
      operationId: updateBookingStatus
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [status]
              properties:
                status:
                  type: string
                  enum: [confirmed, cancelled, completed]
                cancellationReason:
                  type: string
      responses:
        '200':
          description: Status updated
        '400':
          description: Invalid status transition
        '403':
          description: Not authorized to update status

  /bookings/{bookingId}/cancel:
    post:
      summary: Cancel booking
      operationId: cancelBooking
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [reason]
              properties:
                reason:
                  type: string
      responses:
        '200':
          description: Booking cancelled
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  refundAmount:
                    type: number
                  refundStatus:
                    type: string
                    enum: [pending, processed]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Booking:
      type: object
      properties:
        id:
          type: string
          format: uuid
        instrumentId:
          type: string
          format: uuid
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        totalCost:
          type: number
        status:
          type: string
          enum: [pending, confirmed, active, completed, cancelled]
        createdAt:
          type: string
          format: date-time

    BookingDetail:
      allOf:
        - $ref: '#/components/schemas/Booking'
        - type: object
          properties:
            instrument:
              type: object
            renter:
              type: object
            owner:
              type: object
            dailyRate:
              type: number
            deliveryMethod:
              type: string
            deliveryAddress:
              type: object
            paymentStatus:
              type: string
            updatedAt:
              type: string
              format: date-time

