openapi: 3.0.3
info:
  title: Search Service API
  description: Handles full-text search, filtering, and discovery
  version: 1.0.0

servers:
  - url: https://api.laviolin.com/v1

paths:
  /search:
    get:
      summary: Global search
      operationId: globalSearch
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: Search query
        - name: type
          in: query
          schema:
            type: string
            enum: [instruments, users, all]
            default: all
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: object
                    properties:
                      instruments:
                        type: array
                        items:
                          type: object
                      users:
                        type: array
                        items:
                          type: object
                  pagination:
                    type: object

  /search/suggest:
    get:
      summary: Get search suggestions
      operationId: getSearchSuggestions
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Suggestions
          content:
            application/json:
              schema:
                type: object
                properties:
                  suggestions:
                    type: array
                    items:
                      type: object
                      properties:
                        text:
                          type: string
                        type:
                          type: string
                        count:
                          type: integer

  /filters:
    get:
      summary: Get available filters
      operationId: getAvailableFilters
      responses:
        '200':
          description: Available filters
          content:
            application/json:
              schema:
                type: object
                properties:
                  types:
                    type: array
                    items:
                      type: string
                  brands:
                    type: array
                    items:
                      type: string
                  conditions:
                    type: array
                    items:
                      type: string
                  priceRange:
                    type: object
                    properties:
                      min:
                        type: number
                      max:
                        type: number
                  locations:
                    type: array
                    items:
                      type: object
                      properties:
                        city:
                          type: string
                        state:
                          type: string
                        count:
                          type: integer

  /search/popular:
    get:
      summary: Get popular searches
      operationId: getPopularSearches
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Popular searches
          content:
            application/json:
              schema:
                type: object
                properties:
                  searches:
                    type: array
                    items:
                      type: object
                      properties:
                        query:
                          type: string
                        count:
                          type: integer

